company_name = input()
address = input()
phone_numb = input()
fax_number = input()
web_site = input()
manager_first_name = input()
manager_last_name = input()
manager_age = int(input())
manager_phone_number = input()

print(company_name)
print("Address: " + address)
print("Tel. " + phone_numb)
print("Fax: " + fax_number)
print("Web site: " + web_site)
print(f"Manager: {manager_first_name} {manager_last_name} (age: {manager_age}, tel. {manager_phone_number})")
